name: Update "raw" branch

on:
  push:
    branches: [ master ]
    paths:
      - 'a/b/**'
      - '.github/workflows/update.yml'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update "raw" branch
        env:
          DIRECTORY: "./a/b"
        run: |
          gitdir=`mktemp -d`
          moddir=`mktemp -d`

          git clone "https://github.com/$GITHUB_REPOSITORY.git" "$gitdir" --depth=1 --progress --single-branch --verbose
          cd "$gitdir"

          git config advice.detachedHead false
          git checkout --force "$GITHUB_SHA"

          mv -vf "$gitdir/$DIRECTORY"/* $moddir

          cd "$moddir"

          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"

          echo "This is an automated branch/directory. Please do not commit to or change any files in it." >> README

          git add . -v

          commit=`
            curl \
              -s \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA"
          `

          echo "$commit" | jq ".commit.author.name" | xargs git config user.name
          echo "$commit" | jq ".commit.author.email" | xargs git config user.email

          git branch -m raw

          git commit --verbose -m "
          $GITHUB_SHA
          
          This is an automated commit. It is made by a GitHub workflow.
          It contains the \`$DIRECTORY\` directory of the master branch of this repository.
          Action: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          "

          git push origin raw --force --verbose

          cd ~

          rm -rf "$gitdir"
          rm -rf "$moddir"

